[project]
site_name = "Site de suivi &ndash; Projet IFT3150"
site_description = "Template de site web pour le cours IFT3150"
site_author = "Louis-Edouard Lafontant"
site_url = "https://ift3150-template.github.io"

copyright = """
&copy; 2026 <b>DIRO</b> &ndash; Template de site pour le cours IFT3150 <br>
Département d'informatique et de recherche opérationnelle <br>
Université de Montréal
"""

repo_name = "ift3150-template"
repo_url = "https://github.com/ift3150-template/ift3150-template.github.io"

# edit_uri = "edit/main/docs/"

nav = [
  { "Vue d'ensemble" = "index.md" },
  { "Suivi" = "suivi.md" },
  { "Synthèse" = "synthese.md" },
  { "Références" = "references.md" },
]


# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

[project.theme]

language = "fr"

features = [
  "navigation.instant",
  "navigation.tabs",
  "navigation.sections",
  "navigation.expand",
  "navigation.top",
  "search.highlight",
  "content.tabs.link",
  "content.code.copy",
  "content.code.annotate",
]
